### ISSUE TITLE
Rewrite README.md

### ISSUE THREAD

**Issue by Aryan-master** [Aryan-master/Techmorphix-FrontEnd-sample-website#6]
Rewrite the README.md in appealing manner.

**Comment by varunwho** [comment]
Can I work on this? If you could provide me some more info

**Comment by Aryan-master** [comment]
Yes for sure👍. you have to make the readme.md/readme document(description doc) ,of the website.

**Comment by varunwho** [comment]
Yea sure I'll make but could me provide the content as in what to write on that

**Comment by Aryan-master** [comment]
try the website on local host. then, give a brief about it what ever you wish. you can refer to any other README file of any repo.
it's a template for tech related news websites. so you can write accordingly. 🙂

**Comment by varunwho** [comment]
Oh okay, will do
